export const FUNCTIONS = {
  "upload-photo": "https://onproduct.pro/api/upload-photo",
  "generate-upload-url": "https://onproduct.pro/api/generate-upload-url",
  "update-activity": "https://onproduct.pro/api/update-activity",
  "blacklist": "https://onproduct.pro/api/blacklist",
  "get-subscriptions": "https://onproduct.pro/api/get-subscriptions",
  "subscribe": "https://onproduct.pro/api/subscribe",
  "profile-photos": "https://onproduct.pro/api/profile-photos",
  "get-conversations": "https://onproduct.pro/api/get-conversations",
  "private-messages": "https://onproduct.pro/api/private-messages",
  "payment-webhook": "https://onproduct.pro/api/payment-webhook",
  "create-payment": "https://onproduct.pro/api/create-payment",
  "add-energy": "https://onproduct.pro/api/add-energy",
  "register": "https://onproduct.pro/api/register",
  "reset-password": "https://onproduct.pro/api/reset-password",
  "login": "https://onproduct.pro/api/login",
  "add-reaction": "https://onproduct.pro/api/add-reaction",
  "get-user": "https://onproduct.pro/api/get-user",
  "create-user": "https://onproduct.pro/api/create-user",
  "admin-users": "https://onproduct.pro/api/admin-users",
  "get-messages": "https://onproduct.pro/api/get-messages",
  "send-message": "https://onproduct.pro/api/send-message",
  "verify-sms": "https://onproduct.pro/api/verify-sms",
  "send-sms": "https://onproduct.pro/api/send-sms"
} as const;